target 'PracticeProjectForWeibo' do

    pod 'AFNetworking', '~> 3.1.0'
    pod 'MJExtension', '~> 3.0.10'
    pod 'SDWebImage', '~> 3.7.6'
    pod 'MJRefresh', '~> 3.1.10'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'Masonry', '~> 1.0.1'

end